export * from './colors';
export * from './coordinates';
export * from './envVariables';
export * from './goodsAssortment';
export * from './icons';
export * from './navMenu';
export * from './paymentMethods';
export * from './regularExpressions';
export * from './timeslots';
